name: snillocmot
favicon: null
layout_spectrum: 0.2040183653589338
typography_spectrum: 0.8816372575238347
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9414274038281292
  lightness: 0.8410347800236195
  saturation: 0.47558924136683345
  rhythmicContrast: 0.6163427894935012
purpose: []
